# _config.yml

title: ISEP CMI Propostas de Tese de Mestrado
description: 
theme: jekyll-theme-primer

# URL settings (optional, helpful for custom domains)
#url: "https://yourusername.github.io"
#baseurl: "" # leave blank if deploying to root

# Markdown and plugin settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Files/folders to exclude from the build (unnecessary for GitHub Pages)
exclude:
  # Scripts
  - scripts/
